apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: "slack"
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 30m

    receivers:
      - name: "slack"
        slack_configs:
          - channel: "#devops-project"
            send_resolved: true
            username: "Prometheus Alert"
            title: "🚨 [{{ .Status | toUpper }}] Prometheus Alert"
            text: "{{ range .Alerts }}*Alert:* {{ .Annotations.summary }}\n*Severity:* {{ .Labels.severity }}\n*Time:* {{ .StartsAt }}\n{{ end }}"
            api_url: "https://slack.com/api/chat.postMessage"
            http_config:
              bearer_token: "xoxb-6800276630727-8535085096964-QdcF3WhFKP4AfcVoiCluBPxY"  # Replace with your actual bot token
    


# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: alertmanager-config
# data:
#   alertmanager.yml: |
#     global:
#       resolve_timeout: 5m

#     route:
#       receiver: "slack"
#       group_wait: 10s
#       group_interval: 10s
#       repeat_interval: 30m

#     receivers:
#       - name: "slack"
#         slack_configs:
#           - channel: "#devops-project"
#             send_resolved: true
#             username: "Prometheus Alert"
#             title: "🚨 [{{ .Status | toUpper }}] Prometheus Alert"
#             text: "{{ range .Alerts }}*Alert:* {{ .Annotations.summary }}\n*Description:* {{ .Annotations.description }}\n*Severity:* {{ .Labels.severity }}\n*Time:* {{ .StartsAt }}\n{{ end }}"
#             api_url: "$SLACK_WEBHOOK_URL"  # Reference the env variable in Alertmanager Deployment
