apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    rule_files:
      - /etc/prometheus/rules/*.yml  # ✅ Updated path

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager-service.default.svc.cluster.local:9093']

    scrape_configs:
      - job_name: 'prometheus-app'
        static_configs:
          - targets: ['prometheus-app-service.default.svc.cluster.local:80']



# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: prometheus-config
#   labels:
#     name: prometheus-config
# data:
#   prometheus.yml: |
#     global:
#       scrape_interval: 5s

#     rule_files:
#       - /etc/prometheus/rules.yml

#     alerting:
#       alertmanagers:
#         - static_configs:
#             - targets: ['alertmanager-service.default.svc.cluster.local:9093']

#     scrape_configs:
#       - job_name: 'prometheus-app'
#         static_configs:
#           - targets: ['prometheus-app-service.default.svc.cluster.local:80']

