apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  labels:
    name: prometheus-rules
data:
  rules.yml: |
    groups:
    - name: test-alerts
      rules:
      - alert: TestAlert
        expr: vector(1)  # Always evaluates to true
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "This is a test alert to verify Alertmanager"
    - name: instance-alerts
      rules:
      - alert: HighRequestRate
        expr: rate(http_requests_total[5m]) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "🚨 High Request Rate Detected"
          description: "The request rate has been above 5 requests per second for the past 2 minutes."

